---
# This collection is initialized by https://github.com/ansible/ansible-creator 24.12.0

# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: "scaleuptechnologies"
name: "zammad_api"
version: 1.0.0
readme: README.md
authors:
  - Melvin Ziemann (@cloucs) <mziemann@scaleuptech.com>

description: Zammad collection for interacting with the Zammad API
license_file: LICENSE
tags: ["zammad", "tools"]
dependencies: {}

repository: https://github.com/scaleup-technologies/ansible-zammad
issues: https://github.com/scaleup-technologies/ansible-zammad/issues

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
