---
name: "tests"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@main
    if: github.event_name == 'pull_request'
  build-import:
    uses: ansible/ansible-content-actions/.github/workflows/build_import.yaml@main
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main
  unit-tests:
    runs-on: ubuntu-latest
    needs:
      - build-import
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core pytest-xdist coverage==7.6.1
      - name: Run ansible-test units
        run: |
          DEST_DIR="${HOME}/tmp/ansible_collections/scaleuptechnologies/zammad"
          mkdir -p "${DEST_DIR}"
          rsync -v --delete -r ./* "${DEST_DIR}/"
          cd "${DEST_DIR}" || exit
          ansible-test units --coverage -vv --python 3.12
      - name: Generate coverage reports
        run: |
          cd "${HOME}/tmp/ansible_collections/scaleuptechnologies/zammad"
          ansible-test coverage html
          ansible-test coverage report
  all_green:
    if: ${{ always() }}
    needs:
      - changelog
      - build-import
      - sanity
      - ansible-lint
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.changelog.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.ansible-lint.result }}',
          '${{ needs.unit-tests.result }}'
          ])"
